theme: jekyll-theme-slate
title: "MegaMind: A Platform for Security & Privacy Extensions for Voice Assistants"
name: "MegaMind: A Platform for Security & Privacy Extensions for Voice Assistants"
show_downloads: true
